# -*- coding: utf-8 -*-
"""AD7(convert_text_into_features) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvObrL-TSgFt-Kcf_-rxPapGF8BFJRYO
"""

Text = "I am learning NLP"

import pandas as pd
pd.get_dummies(Text.split())

text = ["i love NLP and i will learn in 2month"]

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(text)
vector = vectorizer.transform(text)
print(vectorizer.vocabulary_)
print(vector.toarray())

print(vector)

CountVectorizer?

df = pd.DataFrame(data=vector.toarray(),columns=vectorizer.get_feature_names_out())

df

text = 'I am learning NLP'

!pip install textblob

from textblob import TextBlob
TextBlob(text).ngrams(1)

from textblob import TextBlob
TextBlob(text).ngrams(2)

from textblob import TextBlob
TextBlob(text).ngrams(3)

TextBlob(text).ngram(3)
TextBlob(text).ngram(4)

