# -*- coding: utf-8 -*-
"""exctract_from_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw4fRqlbfkrMjxkcxR2dD9EDxX3tOD9n
"""

!pip install python-docx

import docx

doc = open("/content/file.docx", "rb")
document = docx.Document(doc)

docu = " "
for para in document.paragraphs:
    docu += para.text
print(docu)

for i in range(len(document.paragraphs)):
    print("The content of the paragraph"+str(i)+"is :"+document.paragraphs[i].text+"\n")

