# -*- coding: utf-8 -*-
"""Extract_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXwQHyZfkZ6hNg1hTzMYxlUB1JPUpLmN
"""

!pip install PyPDF2

import PyPDF2
from PyPDF2 import PdfFileReader

PyPDF2.__version__

import PyPDF2 ,urllib,nltk
from io import BytesIO
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

wFile = urllib.request.urlopen('https://www.udri.org/pdf/02%20working%20paper%201.pdf')
pdfreader = PyPDF2.PdfReader(BytesIO(wFile.read()))

import nltk
from nltk.corpus import stopwords
nltk.download('punkt_tab')
nltk.download('stopwords')
pageObj = pdfreader.pages[2]
page2 = pageObj.extract_text()

punctuations =['(',')',';',':','[',']',',','...','.']
tokens = word_tokenize(page2)
stop_words = stopwords.words('english')
keywords = [word for word in tokens if not word in stop_words and not word in punctuations]

keywords

name_list = list()
check = ['Mr.','Mrs.','Ms.']
for idx,token in enumerate(tokens):
  if token.startswith(tuple(check)) and idx<(len(tokens)-1):
    name = token+tokens[idx+1]+''+tokens[idx+2]
    name_list.append(name)
print(name_list)

wFile.close()

pdf = open("/content/file1.pdf","rb")
pdf_reader = PyPDF2.PdfReader(pdf)
print("Number of pages:",len(pdf_reader.pages))
page = pdf_reader.pages[1]
print(page.extract_text())
pdf.close()

