# -*- coding: utf-8 -*-
"""LoanEligibility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfKM24_AF1BnkPtgMo2g34001SX81MZ3
"""

import pandas as pd
train = pd.read_csv('/content/train.csv')
train.head

train.shape

train.info()

train.isna().sum()

train.describe()

train.describe(include=[object])

train['Loan_Status'].value_counts()

import seaborn as sns
sns.countplot(x=train['Loan_Status'])

train['Gender'].value_counts()

sns.countplot(x=train['Gender'])

sns.countplot(x=train['Gender'],hue = train['Loan_Status'])

sns.countplot(x='Married',data= train,hue='Loan_Status')

sns.displot(train['LoanAmount'],kde=True)

import matplotlib.pyplot as plt
grid = sns.FacetGrid(train,row='Gender',col='Married',height=3.2,aspect=1.6)
grid.map(plt.hist,'ApplicantIncome',alpha=.5,bins=10)
grid.add_legend()

train['Gender']=train['Gender'].fillna(train['Gender'].mode()[0])

train['Married']=train['Married'].fillna(train['Married'].mode()[0])

train['Dependents']=train['Dependents'].fillna(train['Dependents'].mode()[0])

train['LoanAmount']=train['LoanAmount'].fillna(train['LoanAmount'].mode()[0])

train['Loan_Amount_Term']=train['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0],inplace=True)

train['Credit_History']=train['Credit_History'].fillna(train['Credit_History'].mode()[0],inplace=True)

train.isna().sum()

