# -*- coding: utf-8 -*-
"""TextRank_TextSummarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mvqQzrjmsPyj9CBDp8P2XlyhJTY80Mj
"""

!pip install pytextrank

!python -m spacy download en_core_web_sm

import spacy
import pytextrank

document =""" Not only did it only confirm that the firlm would br unfunny
and generic, but it also managed to give away the ENTIRE movie;
and i'm not exagggerating - every moment ,every
plot point ,every joke in the trailer."""

en_nlp = spacy.load("en_core_web_sm")
en_nlp.add_pipe("textrank")
doc=en_nlp(document)

tr = doc._.textrank
print(tr.elapsed_time)

for combination in doc._.phrases:
  print(combination.text,combination.rank,combination.count)

from urllib.request import urlopen
from bs4 import BeautifulSoup

def get_only_text(url):
  page = urlopen(url)
  soup = BeautifulSoup(page)
  text = '\t'.join(map(lambda p:p.text,soup.find_all('p')))
  print(text)
  return soup.title,text

url="https://en.wikipedia.org/wiki/Natural_language_processing"
text = get_only_text(url)

len(".join(text)")

text[:1000]

!pip install sumy

!pip install lxml.html.clean

from sumy.parsers.html import HtmlParser
from sumy.parsers.plaintext import PlaintextParser
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words
from sumy.summarizers.luhn import LuhnSummarizer

import nltk
nltk.download('punkt_tab')
LANGUAGE = "english"
SENTENCE_COUNT = 3

url="https://en.wikipedia.org/wiki/Computer_vision"

parser = HtmlParser.from_url(url ,Tokenizer(LANGUAGE))

summarizer = LsaSummarizer(Stemmer(LANGUAGE))
summarizer.stop_words = get_stop_words(LANGUAGE)
for sentence in summarizer(parser.document,5):
  print(sentence)

text =""" India has a robust system to tackle pandemics and public health emergencies, as asserted by the Union Health and Family Welfare Minister.

The country's successful response to COVID-19 has been attributed to effective leadership and communication, fostering a sense of self-confidence and pride among Indians.

The surge in government school enrolment witnessed during the pandemic has reversed, with the proportion of children enrolled in government schools nearly back to 2018 levels """

!pip install sumy
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer

parser = PlaintextParser.from_string(text,Tokenizer("english"))

from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.utils import get_stop_words
summarizer_lex =LexRankSummarizer()

summarizer_lex.stop_words = get_stop_words("english")
summary = summarizer_lex(parser.document, 5)
lex_summary=" "
for sentence in summary:
  lex_summary += str(sentence)
print(lex_summary)

