# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rnfZDSCOF1PSQTrOtCkLP2NETDPNAC-
"""

import nltk
import re
from nltk.chat.util import Chat, reflections

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

import nltk
from nltk.chat.util import Chat, reflections
pairs = [
    (r"hi|hello|hey", ["Hello!", "Hi there!", "Hey!"]),
    (r"how are you?", ["I'm good, thanks!", "Doing well, what about you?"]),
    (r"what is your name?", ["I'm a chatbot!", "Call me ChatBot."]),
    (r"quit", ["Bye! Have a great day!"])
]
chatbot = Chat(pairs, reflections)
def chat_with_bot():
    print("Hi, I'm your chatbot. Type 'quit' to exit.")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("Chatbot: Bye! Have a great day!")
            break
        response = chatbot.respond(user_input)
        print(f"Chatbot: {response}")

chat_with_bot()

